### ISSUE TITLE
Enable cost-explorer

### ISSUE THREAD

**Issue by aterrel** [numfocus/infrastructure#1]
As reported by @bryevdv, bokeh received this message.

>  Your account is a part of consolidated billing. For you to be able to use Cost Explorer, your Payer account needs to enable Cost Explorer.

Investigate and report how to proceed here.

**Comment by bryevdv** [comment]
So technically speaking I seem to be able to access Cost Explorer, but there is no actual data available. It has said:

> It can take up to 4 days for AWS Cost Explorer data to become available. Please try again soon.

For nearly two weeks.

**Comment by aterrel** [comment]
Okay I hit the button on the Cost Explorer to enable. As discussed in this documentation: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ce-enable.html

I'm now seeing this message on the Billing page.

![Screen Shot 2020-06-04 at 8 59 00 AM](https://user-images.githubusercontent.com/30583/83766177-adf7ba80-a641-11ea-8aa1-97746b67cd9b.png)

**Comment by bryevdv** [comment]
@aterrel OK I can see data in the cost explorer now! However, none of our tags area visible, so we can't e.g. break down CDN costs by distribution at all. I think you need to do this:

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html

When I try it says "Access Denied Cost allocation tags are managed at the payer account level."

**Comment by aterrel** [comment]
Hmm. I guess I have to add the tags individually, doesn't have a single toggle. Can you give me a list?

**Comment by bryevdv** [comment]
Really?! Ugh that's annoying as hell. I will have to collect the list and post back here

**Comment by aterrel** [comment]
Well can you start by giving me a few and we can make sure they are viewable on your side?

**Comment by bryevdv** [comment]
Cloudfront-Name is one

**Comment by aterrel** [comment]
I think I'll close this as I think it is either fixed or won't fix.

**Comment by bryevdv** [comment]
I was never able to try the asking account the invite expired.
