### ISSUE TITLE
Switch off servers that are not in use

### ISSUE THREAD

**Issue by datapythonista** [numfocus/infrastructure#13]
Some servers doesn't seem to be in use anymore. We should double check this is the case, and then cancel them. So far, looks like those are the candidates (listing rackspace service names):

- `amy` NumFOCUS internal tool for workshops not in use anymore, as confirmed by Andy
- `bokeh` (confirmed by Bryan this is not being used)
- `scipy-mail` and `mail2.scipy.org` (acoording to [this scipy wiki](https://github.com/scipy/scipy/wiki/Web-service-infrastructure#mailscipyorg) this is not being used since 2018. Didrik doesn't know about those servers)
- `researchcompendia.org` ([repos of the site](https://github.com/researchcompendia) haven't been updated since 2014, I guess it's save to assume this can be switched off)
- `pydata-org` (old PyData site based in Django: https://github.com/pydata/pydata.org. there shouldn't be anything useful here)
- `dask2021`, `eindhoven2021`, `global2021` and `jupytercon2020` once #12 is completed
- `pydata.org-2` once #15 is completed
- `berlin.pydata.org` once #16 is completed

**Comment by martey** [comment]
berlin.pydata.org is the server behind https://berlin.pydata.org/. It looks to be running both Jekyll and a Mezzanine instance. This is probably a better candidate for migration than outright removal.

**Comment by aterrel** [comment]
amy and researchcompendia.org is clearly no longer used. I plan on imaging and shutting down today.

**Comment by aterrel** [comment]
as @datapythonista mentioned in slack, we can also turn off bokeh, scipy-mail, mail2.scipy.org, and pydata-org

**Comment by aterrel** [comment]
Rackspace ticket for the deletion: https://portal.rackspace.com/891151/tickets/details/220405-ord-0001045

They want to run their own scream test. The only way to delete servers these days is to call them or make a support ticket.

**Comment by aterrel** [comment]
These servers are now off.

**Comment by datapythonista** [comment]
The next servers should be ready to be switched off (will wait until Monday to make sure everything is working as expected after the last changes):

- eindhoven2021
- global2021
- conference.scipy.org
- berlin.pydata.org
- pydata.org-2

They are costing $335/month.

@aterrel if I need any information not in the rackspace dashboard when I call, please let me know. Or if it's easier to call yourself, surely fine.

@martey if you want to export the database of global2021 or eindhoven2021 before we get rid of the servers, now it's the time. :)

**Comment by aterrel** [comment]
I don’t think you will need any more information.

**Comment by aterrel** [comment]
closing as we are going to run another audit with @mattnumfocus
