### ISSUE TITLE
Set up domain osaka.pydata.org

### ISSUE THREAD

**Issue by kozo2** [numfocus/infrastructure#17]
### project

PyData Osaka community

### Update existing subdomain?

- [ ] This request is for updating the DNS of an EXISTING subdomain

### Subdomain

osaka.pydata.org

### DNS

CNAME pydataosaka.github.io

### Observations

This request is to make our https://pydataosaka.github.io/ accessible on https://osaka.pydata.org/.

If it is necessary to transfer https://github.com/PyDataOsaka/pydataosaka.github.io from our organization to https://github.com/pydata, we are happy to do so.

**Comment by datapythonista** [comment]
I set it up. You need to go to the settings of your projects, in the `Pages` section and set up the custom domain there. From the domain side seems to be redirecting to GitHub already.

**Comment by kozo2** [comment]
Thanks🙏 @datapythonista !
Now we can see https://pydataosaka.github.io/ with osaka.pydata.org !

**Comment by datapythonista** [comment]
If you haven't already, make aure you generate the ssl certificate and force https in the GitHub pages settings :)

**Comment by kozo2** [comment]
Thank you for the information!
I enabled the "Enforce HTTPS" in GitHub Pages settings!
