### ISSUE TITLE
credits for CI

### ISSUE THREAD

**Issue by orbeckst** [numfocus/infrastructure#20]
### Project

MDAnalysis

### Observations

We are seeking funds to cover some of our recent losses in free CI provisions (i.e., Cirrus CI, to check against "exotic" architectures) and to obtain access to high core count GitHub actions machines. The latter would support work done by one of our recent Google Summer of Code students on [enabling the large scale parallelism of the MDAnalysis library on HPC platforms](https://marinegor.github.io/posts/2023/06/gsoc-summary).

TOTAL **$970.00** : CI costs for a one year period, broken down as follows:
* $600.00: Cirrus CI tokens

   We use 50-100 Cirrus CI tokens per month, 50 of which will be free moving forward. 50 extra tokens ($50) per month would allow us to retain CI services.
* $370.00: GitHub Actions
 
  We can access GitHub large runners (as a CI service to accommodate multithreaded work) for $0.256 per minute (64 cores, Linux). We estimate needing approximately 2 hours of CI per month.

**Comment by aterrel** [comment]
@orbeckst thanks for posting. The infra committee is building our budget request now and will add this request.

**Comment by aterrel** [comment]
@orbeckst  we have approved budgets now, will be reaching out to flesh out how we want to work together with other projects with a similar need.

**Comment by orbeckst** [comment]
Thanks for the update. Sounds good!Am 3/20/24 um 11:05 schrieb Andy R. Terrel ***@***.***>:﻿
@orbeckst  we have approved budgets now, will be reaching out to flesh out how we want to work together with other projects with a similar need.

**Comment by aterrel** [comment]
closing as we are going to add these details to the CI/CD guide we are writing.
