### ISSUE TITLE
pandata.pydata.org

### ISSUE THREAD

**Issue by jbednar** [numfocus/infrastructure#21]
### project

Pandata

### Update existing subdomain?

- [ ] This request is for updating the DNS of an EXISTING subdomain

### Subdomain

pandata

### DNS

I'm not sure what DNS records would be involved, but we were hoping that pandata.pydata.org could point to https://github.com/panstacks/pandata  for now until we get a proper website set up.

### Observations

I run the NumFocus fiscally sponsored project "HoloViz". We've recently realized that we need a name to talk about a much larger set of projects of which HoloViz is a part, and so we've created Pandata as a concept. Pandata is mostly a subset of the PyData ecosystem, focusing on tools for data analysis that scale to very large data sizes. I'd like to set up a steering council for Pandata and get people on board to handle governance, but in the meantime to get it off the ground we just need some sort of web presence to point people to. So if pandata.pydata.org would go _somewhere_ that talks about it, we can get the process started to get the rest of these things in place. Hope that works!

**Comment by nicole-numfocus** [comment]
@jbednar Thanks so much for your patience while we established the workflow in for these requests. 

There is a question of whether this request is applicable since Pandata is not currently a sponsored project with NumFOCUS. It might be helpful to get some context as to how Pandata interacts with other NumFOCUS projects.

The committee is reviewing and will update you once a decision has been made.

**Comment by aterrel** [comment]
We need to figure out how to make this work. If it can use our current cloudflare + github pages infr then I think it is easy to support.

Can you add me as an owner of the org to set it up?

**Comment by jbednar** [comment]
Thanks! Was that a question for me? If so, I've invited you to join the
"panstacks" org where the pandata repo
<https://github.com/panstacks/pandata> sits. Ideally the repo would sit at
the pydata org.

Jim

**Comment by jbednar** [comment]
Any updates?

**Comment by jbednar** [comment]
Still no updates?

**Comment by aterrel** [comment]
I must have missed the invitation. Sorry about that.

I've pointed cloudflare to the domain but I need you to set up the github setting: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

```
$ dig pandata.pydata.org +nostats +nocomments +nocmd

; <<>> DiG 9.10.6 <<>> pandata.pydata.org +nostats +nocomments +nocmd
;; global options: +cmd
;pandata.pydata.org.            IN      A
pandata.pydata.org.     300     IN      A       172.67.71.236
pandata.pydata.org.     300     IN      A       104.26.1.204
pandata.pydata.org.     300     IN      A       104.26.0.204
```

**Comment by jbednar** [comment]
Thanks. It works!
[image: image.png]
