### ISSUE TITLE
Cirrus CI credits across projects

### ISSUE THREAD

**Issue by rgommers** [numfocus/infrastructure#22]
### Project

NumPy, SciPy

### Observations

Quite a few projects use Cirrus CI, as it is a well-designed service and still the only one to offer macOS arm64 (M1) support (as well as FreeBSD, which we use in NumPy as well). I'll xref gh-20, where Cirrus CI is the majority of the MDAnalysis request.

The problem with paying for credits is not the hundreds of dollars per year (maybe up to $1,000) for our projects. It's much more the logistics of buying credits for each project, getting reimbursed, etc. If a centrally negotiated/purchased request for a set of, or all of the, NumFOCUS projects could make that a lot easier, then I'm sure maintainers would appreciate that.

**Comment by aterrel** [comment]
@rgommers we have approved budgets now, will be reaching out to flesh out how we want to work together with other projects with a similar need.

**Comment by rgommers** [comment]
Sounds great!

**Comment by aterrel** [comment]
closing this, will add to CI/CD guide how to get a credit card from NF to pay for such costs.
