### ISSUE TITLE
Checkbox Selection Triggers Page Refresh and Resets Scroll Position

### ISSUE THREAD

**Issue by AquibKhann** [numfocus/infrastructure#23]
When attempting to check a checkbox on the NumFOCUS website, the action triggers an unexpected page refresh, leading to an inconvenience as the scroll position resets to the top of the page. This behavior prevents users from efficiently selecting multiple checkboxes in one session. 
This issue is reproducible on chrome browser and try to check the boxes in project menu.

Screen Recording of the bug

https://github.com/numfocus/infrastructure/assets/120818337/ea6861bf-9199-40ee-84e8-c6aeb03eafc8

**Comment by AquibKhann** [comment]
Maintainers please let me know whether this project is still active or not.

**Comment by nicole-numfocus** [comment]
Thanks for the ping! I'll get this sorted with our marketing folks who manage the website.

**Comment by nicole-numfocus** [comment]
@AquibKhann it should be corrected. Would you mind testing? Let me know if you see any more issues. Thanks!

**Comment by AquibKhann** [comment]
@nicole-numfocus Thank you for your swift response and for addressing the issue. I will test the corrections as soon as possible and let you know the results.
