### ISSUE TITLE
Bug: Open Source Sustainability - "Learn More" link leads to 404 Page

### ISSUE THREAD

**Issue by AquibKhann** [numfocus/infrastructure#24]
Description:
Issue:
Clicking on the "Learn More" link under Open Source Sustainability on the NumFOCUS website leads to a 404 Page. The page is empty, and the message "No Results Found" is displayed.

Steps to Reproduce:

Visit the NumFOCUS website.
Navigate to the "Open Source Sustainability" section.
Click on the "Learn More" link.
Expected Result:
The "Learn More" link should lead to the relevant content on Open Source Sustainability.

Actual Result:
The link results in a 404 Page with the message "No Results Found."

This issue impacts the accessibility of information related to Open Source Sustainability, and I believe addressing it would improve the user experience on the NumFOCUS website.

https://github.com/numfocus/infrastructure/assets/120818337/efbfae0a-dd33-4336-a5cc-5aaa17b95460

**Comment by nicole-numfocus** [comment]
Thanks for bringing this to our attention! I'll get with the website team.

**Comment by AquibKhann** [comment]
Firstly, I want to express my gratitude for the acknowledgment and thanks in response to my recent  reported issues. It's been a valuable experience working on Numfocus Open Source Project, and I appreciate the support.
Given my growing interest and commitment to contributing to the project, I am considering participating in Google Summer of Code 2024. I believe that having a mentor with your expertise and guidance would greatly enhance my learning experience and contribution potential.
I understand that mentoring is a significant commitment, and I would be honored if you could consider being my mentor for GSoC 2024. Your guidance would undoubtedly contribute to my growth as a contributor, and I am eager to take on the challenges and contribute meaningfully to the project.
Of course, I understand that you have other commitments, and if you are unable to take on the role of a mentor, I completely respect that. Regardless of your decision, I will continue to contribute to Numfocus Open Source Project and learn from the vibrant community.

Thank you for considering my request, and I look forward to your response.

**Comment by MridulS** [comment]
@AquibKhann it's great to see your enthusiasm! NumFOCUS is an umbrella organisation (it is not an open source project). To learn more about the how this works you can look at https://github.com/numfocus/gsoc

Please reach out to projects directly https://github.com/numfocus/gsoc#organizations-confirmed-under-numfocus-umbrella if you find projects that you find interesting. Just keep in mind it's still early of GSoC and the projects that participated last year may or may not participate next year.

**Comment by AquibKhann** [comment]
@MridulS  Thank you so much for your guidance , I get it now .

**Comment by nicole-numfocus** [comment]
@AquibKhann The website has been updated. Thanks again for raising this
