### ISSUE TITLE
FEniCS Project Larger static hosting

### ISSUE THREAD

**Issue by jhale** [numfocus/infrastructure#25]
We have nearly migrated our site https://fenicsproject.org to GitHub Pages, but we have some larger files of historic interest at https://fenicsproject.org/pub/ and https://fenicsproject.org/olddocs/ that we do not want/cannot keep under version control.

In terms of resources talking 10s of GBs of data and low volume (10s-100s GB a year downloaded).

Keeping the URL would be nice but appreciate it may not be possible. Subdomains could work.

**Comment by MridulS** [comment]
Hmm, if this doesn't need to be accessed much  maybe this could be hosted via [Clouflare R2](https://www.cloudflare.com/developer-platform/r2/)?

**Comment by aterrel** [comment]
@jhale would cloudflare R2 or AWS S3 solve your need?

**Comment by aterrel** [comment]
@jhale let me know if this is still a need?

**Comment by aterrel** [comment]
Closing do to lack of response.
