### ISSUE TITLE
Bug: Navigation Menu Highlighting Issue in Numfocus Website - Project Dropdown Highlights Programs Dropdown

### ISSUE THREAD

**Issue by AquibKhann** [numfocus/infrastructure#26]
In the Numfocus website's navigation menu, there is a highlighting issue where clicking on the "Project" dropdown not only activates the corresponding dropdown but also unintentionally highlights the "Programs" dropdown. This behavior can cause confusion and impacts the expected navigation flow.

Steps to Reproduce:

Visit the Numfocus website.
Navigate to the navigation menu.
Hover over the "Project" dropdown.
Observe that both the "Project" and "Programs" dropdowns are highlighted.
Expected Result:
Clicking on the "Project" dropdown should only activate and highlight the "Project" dropdown, not affect the highlighting of other dropdowns.

Actual Result:
Clicking on the "Project" dropdown also highlights the "Programs" dropdown, leading to an unintended visual interaction.

https://github.com/numfocus/infrastructure/assets/120818337/77d90004-8c1c-4fb3-9dec-0d391b22acf6

**Comment by nabobalis** [comment]
Hello @AquibKhann,

Thank you for reporting this and this has been raised to the team that handles the website. 
We have no ETA when this will be fixed but it is a known issue to them and they will handle it.
